# Databricks Config pipeline for Azure DevOps
pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - devops

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - devops

# Global Variables. For environment-specific variables, see the individual stages further below e.g. Release_Dev, Release_Uat, etc.
variables:
  - name: AGENT_POOL
    value: "This is a placeholder for your private agent pool" #The name of the Azure DevOps agent pool
  - name: condition
    value: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))" #Check if the build has succeeded and the source branch is main
  - name: DATABRICKS_SDK_VERSION # the version of the Databricks SDK to install https://pypi.org/project/databricks-sdk/#history
    value: "0.28.0"
  - name: DATABRICKS_LOG_LEVEL #Logging level for Databricks CLI e.g. 'debug', 'warn', 'info' https://docs.databricks.com/en/dev-tools/cli/troubleshooting.html
    value: "warn" #log messages at the warn and error levels.

#Import Azure DevOps variable group values containing secrets and other variables
  - group: placeholder-for-devops-library-name #replace with the name of your Azure DevOps library

stages:
  - stage: Build_Dev
    displayName: "Build Dev"
    dependsOn: []
    jobs:
      - template: /devops/templates/ado-build-template.yml@self
        parameters:
          BUNDLE_TARGET: "dev"
          ADB_HOST: $(ADB_DEV_HOST)
          ADB_CLIENT_ID: $(ADB_DEV_SPN_ID)
          ADB_CLIENT_SECRET: $(ADB_DEV_SPN_SECRET)
          DATABRICKS_SDK_VERSION: ${{ variables.DATABRICKS_SDK_VERSION }}
          DATABRICKS_LOG_LEVEL: ${{ variables.DATABRICKS_LOG_LEVEL }}
          ADO_ENVIRONMENT: "Dev-Databricks" #Update this to desired environment name in Azure DevOps
          AGENT_POOL: ${{ variables.AGENT_POOL }}

  - stage: Release_Dev
    displayName: "Release Dev"
    dependsOn: [Build_Dev]
    condition: ${{ variables.Condition }}
    jobs:
      - template: /devops/templates/ado-release-template.yml@self
        parameters:
          BUNDLE_TARGET: "dev"
          ADB_HOST: $(ADB_DEV_HOST)
          ADB_CLIENT_ID: $(ADB_DEV_SPN_ID)
          ADB_CLIENT_SECRET: $(ADB_DEV_SPN_SECRET)
          ADB_ENABLE_IP_ACCESS_LISTS: false #Update to true if you want to enable IP access lists for the Databricks workspace
          DATABRICKS_SDK_VERSION: ${{ variables.DATABRICKS_SDK_VERSION }}
          DATABRICKS_LOG_LEVEL: ${{ variables.DATABRICKS_LOG_LEVEL }}
          ADB_JOB_NAMES: "init_job" #Update this to desired init job name defined in your YAML file
          ADO_ENVIRONMENT: "Dev-Databricks" #Update this to desired environment name in Azure DevOps
          AGENT_POOL: ${{ variables.AGENT_POOL }}

  - stage: Build_Uat
    displayName: "Build Uat"
    dependsOn: []
    jobs:
      - template: /devops/templates/ado-build-template.yml@self
        parameters:
          BUNDLE_TARGET: "uat"
          ADB_HOST: $(ADB_UAT_HOST)
          ADB_CLIENT_ID: $(ADB_UAT_SPN_ID)
          ADB_CLIENT_SECRET: $(ADB_UAT_SPN_SECRET)
          DATABRICKS_SDK_VERSION: ${{ variables.DATABRICKS_SDK_VERSION }}
          DATABRICKS_LOG_LEVEL: ${{ variables.DATABRICKS_LOG_LEVEL }}
          ADO_ENVIRONMENT: "Uat-Databricks" #Update this to desired environment name in Azure DevOps
          AGENT_POOL: ${{ variables.AGENT_POOL }}

  - stage: Release_Uat
    displayName: "Release Uat"
    dependsOn: [Build_Uat]
    condition: succeeded()
    jobs:
      - template: /devops/templates/ado-release-template.yml@self
        parameters:
          BUNDLE_TARGET: "uat"
          ADB_HOST: $(ADB_UAT_HOST)
          ADB_CLIENT_ID: $(ADB_UAT_SPN_ID)
          ADB_CLIENT_SECRET: $(ADB_UAT_SPN_SECRET)
          ADB_ENABLE_IP_ACCESS_LISTS: false #Update to true if you want to enable IP access lists for the Databricks workspace
          DATABRICKS_SDK_VERSION: ${{ variables.DATABRICKS_SDK_VERSION }}
          DATABRICKS_LOG_LEVEL: ${{ variables.DATABRICKS_LOG_LEVEL }}
          ADB_JOB_NAMES: "init_job" #Update this to desired init job name defined in your YAML file
          ADO_ENVIRONMENT: "Uat-Databricks" #Update this to desired environment name in Azure DevOps
          AGENT_POOL: ${{ variables.AGENT_POOL }}          

  - stage: Build_PFX
    displayName: "Build PFX"
    dependsOn: []
    jobs:
      - template: /devops/templates/ado-build-template.yml@self
        parameters:
          BUNDLE_TARGET: "pfx"
          ADB_HOST: $(ADB_PFX_HOST)
          ADB_CLIENT_ID: $(ADB_PFX_SPN_ID)
          ADB_CLIENT_SECRET: $(ADB_PFX_SPN_SECRET)
          DATABRICKS_SDK_VERSION: ${{ variables.DATABRICKS_SDK_VERSION }}
          DATABRICKS_LOG_LEVEL: ${{ variables.DATABRICKS_LOG_LEVEL }}
          ADO_ENVIRONMENT: "ProdFix-Databricks" #Update this to desired environment name in Azure DevOps
          AGENT_POOL: ${{ variables.AGENT_POOL }}

  - stage: Release_PFX
    displayName: "Release PFX"
    dependsOn: [Build_PFX]
    condition: ${{ variables.Condition }}
    jobs:
      - template: /devops/templates/ado-release-template.yml@self
        parameters:
          BUNDLE_TARGET: "pfx"
          ADB_HOST: $(ADB_PFX_HOST)
          ADB_CLIENT_ID: $(ADB_PFX_SPN_ID)
          ADB_CLIENT_SECRET: $(ADB_PFX_SPN_SECRET)
          ADB_ENABLE_IP_ACCESS_LISTS: false #Update to true if you want to enable IP access lists for the Databricks workspace
          DATABRICKS_SDK_VERSION: ${{ variables.DATABRICKS_SDK_VERSION }}
          DATABRICKS_LOG_LEVEL: ${{ variables.DATABRICKS_LOG_LEVEL }}
          ADB_JOB_NAMES: "init_job" #Update this to desired init job name defined in your YAML file
          ADO_ENVIRONMENT: "ProdFix-Databricks" #Update this to desired environment name in Azure DevOps
          AGENT_POOL: ${{ variables.AGENT_POOL }}

  - stage: Build_PRD
    displayName: "Build PRD"
    dependsOn: []
    jobs:
      - template: /devops/templates/ado-build-template.yml@self
        parameters:
          BUNDLE_TARGET: "prd"
          ADB_HOST: $(ADB_PRD_HOST)
          ADB_CLIENT_ID: $(ADB_PRD_SPN_ID)
          ADB_CLIENT_SECRET: $(ADB_PRD_SPN_SECRET)
          DATABRICKS_SDK_VERSION: ${{ variables.DATABRICKS_SDK_VERSION }}
          DATABRICKS_LOG_LEVEL: ${{ variables.DATABRICKS_LOG_LEVEL }}
          ADO_ENVIRONMENT: "Prod-Databricks" #Update this to desired environment name in Azure DevOps
          AGENT_POOL: ${{ variables.AGENT_POOL }}

  - stage: Release_PRD
    displayName: "Release PRD"
    dependsOn: [Build_PRD]
    condition: ${{ variables.Condition }}
    jobs:
      - template: /devops/templates/ado-release-template.yml@self
        parameters:
          BUNDLE_TARGET: "prd"
          ADB_HOST: $(ADB_PRD_HOST)
          ADB_CLIENT_ID: $(ADB_PRD_SPN_ID)
          ADB_CLIENT_SECRET: $(ADB_PRD_SPN_SECRET)
          ADB_ENABLE_IP_ACCESS_LISTS: false #Update to true if you want to enable IP access lists for the Databricks workspace
          DATABRICKS_SDK_VERSION: ${{ variables.DATABRICKS_SDK_VERSION }}
          DATABRICKS_LOG_LEVEL: ${{ variables.DATABRICKS_LOG_LEVEL }}
          ADB_JOB_NAMES: "init_job" #Update this to desired init job name defined in your YAML file
          ADO_ENVIRONMENT: "Prod-Databricks" #Update this to desired environment name in Azure DevOps
          AGENT_POOL: ${{ variables.AGENT_POOL }}
